using System.Text.Json;

namespace TennisClub.Shared.Messages;

/// <summary>
/// The envelope the CLIENT sends to the SERVER over the WebSocket.
///<br/>
/// Key WebSocket concept:
///   WebSocket is a full-duplex channel. Unlike HTTP, there is no built-in
///   request/response pairing. We therefore add a <see cref="RequestId"/>
///   (a GUID string) to every outgoing message. The server echoes that same
///   RequestId back in its <see cref="WebSocketResponse"/>, allowing the
///   client to match each response to the call that triggered it.
/// </summary>
public class WebSocketMessage
{
    // A unique ID generated by the client for every outgoing call.
    // Acts like the implicit correlation built into HTTP request/response.
    public string RequestId { get; set; } = Guid.NewGuid().ToString();

    // Tells the server WHAT operation is being requested.
    public MessageType Type { get; set; }

    // The operation-specific data, kept as a raw JsonElement so that the
    // server can deserialise it into the correct strongly-typed payload
    // class based on the Type field above.
    public JsonElement? Payload { get; set; }
}
